#!/usr/bin/env bash
# Emits UAT.md with at least 5 human-reviewable steps.
#
# Usage:
#   smoke-uat.sh <output_path> <slot_id> <repo_name> <pinned_sha> <run_date>
#
# Writes a human-reviewable UAT document to <output_path>.
# Exit: 0 on success, 1 on missing argument.

set -euo pipefail

OUTPUT="${1:?usage: smoke-uat.sh <output> <slot_id> <repo_name> <pinned_sha> <run_date>}"
SLOT_ID="${2:?}"
REPO_NAME="${3:?}"
PINNED_SHA="${4:?}"
RUN_DATE="${5:-$(date -u +%Y-%m-%d)}"

cat > "$OUTPUT" <<EOF
# User Acceptance Test — Slot: $SLOT_ID

## Run Identity

| Field | Value |
|-------|-------|
| Slot | $SLOT_ID |
| Repository | $REPO_NAME |
| Pinned SHA | $PINNED_SHA |
| Run Date | $RUN_DATE |

## Purpose

This document provides human-reviewable evidence that the smoke run
completed successfully and produced artifacts that can be audited
without running the pipeline again.

## Human-Reviewable Steps

### Step 1 — Clone Verification

Inspect the cloned repository within the stable output root under the
slot directory.

Confirm that:
- The repository is present and non-empty
- \`git status --porcelain\` is empty (no uncommitted changes)
- \`git log --oneline -1\` matches the reported pinned SHA

### Step 2 — Scan Evidence

Inspect the ast-grep scan output in the evidence/ directory.

Confirm that:
- The file is non-empty
- At least one record is present (symbols detected)

### Step 3 — Ingest Evidence

Inspect the ingest output in the evidence/ directory.

Confirm that:
- The file is valid JSON
- Contains architecture element and relationship counts

### Step 4 — SHA Binding

Inspect the per-doc frontmatter in each generated document.
Each document's first 10 lines must contain:

\`\`\`
pinned_sha: <sha>
pin_source: gh api repos/<owner>/<repo>/commits?per_page=1
campaign_id: <campaign>
slot_id: $SLOT_ID
run_date: $RUN_DATE
\`\`\`

### Step 5 — Cleanup Confirmation

Run the cleanup audit script and confirm zero residue:

\`\`\`bash
scripts/oss/smoke-cleanup-audit.sh
\`\`\`

Expected output: three "empty" results (no containers, no /tmp/ark-smoke-*
directories, no ark-smoke processes).

### Step 6 — Stable Root Structure

Verify the per-slot directory structure under the stable output root:

\`\`\`
<slot>/<date>/
├── RUN_INDEX.md        # Slot-level index with checklist
├── RUN_MANIFEST.yaml   # Machine-readable slot manifest
├── evidence/
│   ├── manifest.txt    # sha256 of all evidence files
│   └── scan.astgrep.jsonl
\`\`\`

## Verdict Criteria

| Criterion | Required | Present |
|-----------|----------|---------|
| Clone size ≤ 1024 MB | Yes | |
| git status --porcelain empty | Yes | |
| AST grep records > 0 | Yes | |
| Frontmatter in first 10 lines | Yes | |
| Cleanup audit: zero residue | Yes | |

## Sign-Off

A smoke run is considered PASS when all five required criteria above
are confirmed. A run that meets some but not all criteria is PARTIAL.

---
Generated by smoke-uat.sh — do not edit manually.
EOF

printf '[smoke-uat] wrote UAT document to %s\n' "$OUTPUT"
