#!/usr/bin/env bash
# Emits UAT.md with at least 5 human-reviewable steps.
#
# Usage:
#   smoke-uat.sh <output_path> <slot_id> <repo_name> <pinned_sha> <run_date>
#
# Writes a human-reviewable UAT document to <output_path>.
# Exit: 0 on success, 1 on missing argument.

set -euo pipefail

OUTPUT="${1:?usage: smoke-uat.sh <output> <slot_id> <repo_name> <pinned_sha> <run_date>}"
SLOT_ID="${2:?}"
REPO_NAME="${3:?}"
PINNED_SHA="${4:?}"
RUN_DATE="${5:-$(date -u +%Y-%m-%d)}"

cat > "$OUTPUT" <<EOF
# User Acceptance Test — Slot: $SLOT_ID

## Run Identity

| Field | Value |
|-------|-------|
| Slot | $SLOT_ID |
| Repository | $REPO_NAME |
| Pinned SHA | $PINNED_SHA |
| Run Date | $RUN_DATE |

## Purpose

This document provides human-reviewable evidence that the smoke run
completed successfully and produced artifacts that can be audited
without running the pipeline again.

## Human-Reviewable Steps

### Step 1 — Clone Verification

Inspect the cloned repository within the stable output root under the
slot directory.

Confirm that:
- The repository is present and non-empty
- \`git status --porcelain\` is empty (no uncommitted changes)
- \`git log --oneline -1\` matches the reported pinned SHA

### Step 2 — Git State Capture (UAT2-001)

Inspect the git-before.txt and git-after.txt files in the stable run root.

Confirm that:
- Both files exist
- Their content is identical (repo was not modified during run)
- This is the UAT2-001 invariant check

### Step 3 — SHA Binding (Pin Match)

Inspect the frontmatter.txt file and RUN_MANIFEST.yaml.

Confirm that:
- frontmatter.txt shows \`pinned_sha: $PINNED_SHA\`
- RUN_MANIFEST.yaml shows \`cloned_sha: <actual>\` matching the cloned commit
- \`pin_match: true\` in RUN_MANIFEST.yaml

### Step 4 — Cleanup Confirmation

Run the cleanup audit script and confirm zero residue:

\`\`\`bash
scripts/oss/smoke-cleanup-audit.sh
\`\`\`

Expected output: three "empty" results (no containers, no /tmp/ark-smoke-*
directories, no ark-smoke processes).

### Step 5 — Evidence Manifest

Inspect the evidence/manifest.txt file.

Confirm that:
- The file is non-empty
- Each line contains a sha256 hash followed by a file path
- All artifact files are listed

### Step 6 — Stable Root Structure

Verify the per-slot directory structure under the stable output root:

\`\`\`
<run-id>/
├── commit.txt          # Cloned git commit SHA
├── frontmatter.txt     # Run frontmatter
├── git-before.txt      # git status --porcelain after clone
├── git-after.txt       # git status --porcelain after pipeline
├── UAT.md              # This document
└── <slot_id>/<date>/
    ├── RUN_INDEX.md        # Slot-level index with checklist
    ├── RUN_MANIFEST.yaml   # Machine-readable slot manifest
    └── evidence/
        ├── manifest.txt    # sha256 of all evidence files
        └── scan.astgrep.jsonl  # (if ast-grep was run)
\`\`\`

## Verdict Criteria

| Criterion | Required | Present |
|-----------|----------|---------|
| Clone size ≤ 1024 MB | Yes | |
| pin_match: true | Yes | |
| uat2_001: true (git status identical) | Yes | |
| evidence/manifest.txt non-empty | Yes | |
| Cleanup audit: zero residue | Yes | |

## Sign-Off

A smoke run is considered PASS when all five required criteria above
are confirmed. A run that meets some but not all criteria is PARTIAL.
A run that fails a hard invariant (pin_match, uat2_001) is FAIL.

---
Generated by smoke-uat.sh — do not edit manually.
EOF

printf '[smoke-uat] wrote UAT document to %s\n' "$OUTPUT"
