"""Application ports (docs/v2/45 §4, V2.3-F4).

Use cases (promotion, proposals, …) depend on these Protocols — never on
ActiveGraph or the concrete world implementation (ADR-0024).
`ArchitectureWorld` satisfies `ArchitectureWorldPort` structurally;
ActiveGraph calls stay inside world.py, behind the domain methods below.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from archskillkit.packs.arch_core import ClaimData, EvidenceData, ObservationData


@runtime_checkable
class ArchitectureWorldPort(Protocol):
    """Domain surface the promotion/proposal use cases may rely on."""

    project_id: str
    project_name: str
    run_id: str

    def find_objects(self, obj_type: str, **data_match) -> list[dict]: ...
    def get_object(self, object_id: str) -> dict: ...
    def record_observation(self, observation: ObservationData) -> str: ...
    def record_evidence(self, evidence: EvidenceData) -> str: ...

    def observation_is_claimed(self, observation_id: str) -> bool: ...
    def propose_derived_claim(self, claim: ClaimData,
                              observation_id: str) -> str: ...
    def claim_observation_ids(self, claim_id: str) -> list[str]: ...
    def link_contradicts(self, observation_id: str, claim_id: str,
                         reason: str) -> None: ...
    def claim_is_contradicted(self, claim_id: str) -> bool: ...
    def set_claim_status(self, claim_id: str, status: str) -> None: ...
    def accept_claim(self, claim_id: str, actor: str = "user") -> None: ...

    def add_architecture_element(self, name: str, kind: str,
                                 origin: str = "DETECTED",
                                 confidence: str = "high") -> str: ...
    def add_architecture_relation(self, kind: str, source_id: str,
                                  target_id: str,
                                  data: dict | None = None) -> str: ...
    def architecture_relations(self) -> list[dict]: ...
    def persist_findings(self, findings: list[dict]) -> int: ...

    def record_proposal(self, name: str, rationale: str = "") -> str: ...
    def set_object_fields(self, object_id: str, fields: dict) -> None: ...
    def remove_relation_by_id(self, relation_id: str) -> None: ...
    def remove_object_by_id(self, object_id: str) -> None: ...
